"""Add status and error_message to Document table

Revision ID: fe1424f03397
Revises: 9ef080b3f75c
Create Date: 2025-09-13 11:05:39.364976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe1424f03397'
down_revision = '9ef080b3f75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('conversion_errors')
    except Exception:
        pass
    try:
        with op.batch_alter_table('chinese_texts', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('pgroonga_content_index'), postgresql_using='pgroonga')
    except Exception:
        pass
    try:
        op.drop_table('chinese_texts')
    except Exception:
        pass

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('conversion_type', sa.Integer(), nullable=True))
        # Add status column with a server_default
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        try:
            batch_op.drop_index(batch_op.f('idx_documents_file_name_gin'), postgresql_ops={'file_name': 'gin_trgm_ops'}, postgresql_using='gin')
        except Exception:
            pass
        try:
            batch_op.drop_index(batch_op.f('idx_documents_markdown_content_gin'), postgresql_ops={'markdown_content': 'gin_trgm_ops'}, postgresql_using='gin')
        except Exception:
            pass
        try:
            batch_op.drop_index(batch_op.f('idx_pgroonga_markdown_content'), postgresql_using='pgroonga')
        except Exception:
            pass
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        try:
            batch_op.drop_column('markdown_content')
        except Exception:
            pass
        try:
            batch_op.drop_column('search_vector')
        except Exception:
            pass
        try:
            batch_op.drop_column('is_converted')
        except Exception:
            pass
    
    # Set a default value for existing rows
    op.execute("UPDATE documents SET status = 'completed' WHERE status = 'pending'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_converted', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.create_index(batch_op.f('idx_pgroonga_markdown_content'), ['markdown_content'], unique=False, postgresql_using='pgroonga')
        batch_op.create_index(batch_op.f('idx_documents_markdown_content_gin'), ['markdown_content'], unique=False, postgresql_ops={'markdown_content': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_documents_file_name_gin'), ['file_name'], unique=False, postgresql_ops={'file_name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')
        batch_op.drop_column('conversion_type')
        batch_op.drop_column('content')

    op.create_table('chinese_texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chinese_texts_pkey'))
    )
    with op.batch_alter_table('chinese_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('pgroonga_content_index'), ['content'], unique=False, postgresql_using='pgroonga')

    op.create_table('conversion_errors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('conversion_errors_pkey'))
    )
    # ### end Alembic commands ###
